FROM glondu/beleniosbase:20230724-1
# alternatively, run "docker build -f Dockerfile_base_environment -t beleniosbase ." and replace with the line below
# FROM beleniosbase

ADD --chown=belenios . /home/belenios/
RUN . /home/belenios/.belenios/env.sh \
    && make build-debug-server

ENV BELENIOS_SENDMAIL=tests/selenium/tools/sendmail_fake_to_static.sh
CMD ./demo/run-server.sh --debug
