#!/bin/sh

set -e

DIR="$1"
shift

NAME="${DIR##*/}"

if [ -d "$DIR/belenios/var" ]; then
    exec systemd-nspawn --image=$DIR/rootfs.squashfs --overlay=+/var::/var --bind-ro=$DIR/belenios/etc:/etc/belenios --bind=$DIR/belenios/var:/var/belenios --machine=belenios-$NAME "$@"
else
    exec systemd-nspawn --image=$DIR/rootfs.squashfs --overlay=+/var::/var --bind=$DIR/belenios:/var/belenios --machine=belenios-$NAME "$@"
fi
